global:
  scrape_interval: 15s

scrape_configs:
  # Monitor User Service
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']  